<a href="https://colab.research.google.com/github/bharath097/2216113_AIML_BOOTCAMP_GRAD-STELLAR/blob/main/2216113_SMS_SPAM_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df=pd.read_csv('/content/drive/MyDrive/SMSSpamCollection',sep='\t', header=None,names=['label','message'])

In [ ]:
df.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.shape

(5572, 2)

In [ ]:
#method 1 - Label Encoder

#method 2:

df['label']=df.label.map({'ham':0,'spam':1})

In [ ]:
df.head()

label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
documents = ["Hello, how are you!",
             'Win money, win from home.',
             'Call me now',
             'Hello, Call hello you tommorow?']

from sklearn.feature_extraction.text import CountVectorizer

count_vector = CountVectorizer()     #calling the method
print(count_vector)

CountVectorizer()


In [ ]:
# fit_transform , transform

count_vector.fit(documents)

CountVectorizer()

In [ ]:
n=count_vector.get_feature_names()
print(n)

['are', 'call', 'from', 'hello', 'home', 'how', 'me', 'money', 'now', 'tommorow', 'win', 'you']


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [ ]:
doc_array = count_vector.transform(documents).toarray()

In [ ]:
#converting array into DataFrame - for understanding
freq_table = pd.DataFrame(data=doc_array,columns=n)

In [ ]:
freq_table

are  call  from  hello  home  how  me  money  now  tommorow  win  you
0    1     0     0      1     0    1   0      0    0         0    0    1
1    0     0     1      0     1    0   0      1    0         0    2    0
2    0     1     0      0     0    0   1      0    1         0    0    0
3    0     1     0      2     0    0   0      0    0         1    0    1

In [ ]:
#load the data
# method 1

x= df.iloc[:,-1:].values    # Independent - message column
y= df.iloc[:,:-1].values   # Dependent - label column

In [ ]:
y

array([[0],
       [0],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
#Split the data for test & train
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1, shuffle=True)

In [ ]:
y_test

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
count_vector = CountVectorizer()

training_data = count_vector.fit_transform(x_train.flatten())

testing_data = count_vector.transform(x_test.flatten())


In [ ]:
training_data

<4457x7714 sparse matrix of type '<class 'numpy.int64'>'
	with 59028 stored elements in Compressed Sparse Row format>

In [ ]:
testing_data

<1115x7714 sparse matrix of type '<class 'numpy.int64'>'
	with 14094 stored elements in Compressed Sparse Row format>

In [ ]:
#from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(training_data,y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier()

In [ ]:
'''y_pred=model.predict(testing_data)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))'''

'y_pred=model.predict(testing_data)\nnp.set_printoptions(precision=2)\nprint(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))'

In [ ]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
print("Predicted value for training data:",model.score(training_data,y_train)*100)
print("Predicted value for testing data:",model.score(testing_data,y_test)*100)

Predicted value for training data: 100.0
Predicted value for testing data: 98.29596412556054


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred) 
print("confusion matrix for testing data")
print(cm) 
accuracy_score(y_test, y_pred) #TN FP FN TP
print("confusion matrix for traning data")
cm1=confusion_matrix(y_train,model.predict(training_data))
print(cm1)

confusion matrix for testing data
[[968   0]
 [ 19 128]]
confusion matrix for traning data
[[3857    0]
 [   0  600]]
