<a href="https://colab.research.google.com/github/bharath097/2216113_AIML_BOOTCAMP_GRAD-STELLAR/blob/main/malaria_outbreak_detection(113).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv(r"/outbreak_detect.csv")


In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
df=df.dropna()

In [6]:
df.head(30)

maxTemp  minTemp  avgHumidity  Rainfall  Positive   pf Outbreak
0      29.0     18.0        49.74      0.00      2156  112       No
1      34.0     23.0        83.27     15.22     10717  677      Yes
2      40.0     23.0        50.74      0.00      1257  127       No
4      34.0     24.0        59.16      9.06      4198  211       No
5      34.0     27.0        73.23      0.00     11808  712      Yes
6      31.0     24.0        88.77     41.40     10881  648      Yes
7      33.0     24.0        77.94     23.88      8830  459      Yes
8      31.0     24.0        84.57     11.15      9693  482       No
9      36.0     24.0        53.40      2.12      9310  549       No
10     32.0     23.0        57.50      0.00     13154  838      Yes
11     34.0     18.0        59.40      0.00      2197  136       No
12     42.0     24.0        49.43      2.19      3362  213       No
13     45.0     32.0        34.74      0.38       416   26       No
14     43.0     28.0        69.07      4.65      7514  410       No
15     33.0     23.0        80.97      6.92     10990  390      Yes
16     32.0     24.0        87.32     11.92      6536  338       No
17     40.0     27.0        63.97      0.00     11169  776      Yes
19     39.0     25.0        47.52      0.00      8131  312       No
20     36.0     26.0        72.78      3.54      5138  213       No
21     31.0     23.0        73.35      4.97     10659  612      Yes
22     30.0     23.0        86.81      7.21      9041  418       No
23     30.0     22.0        78.80      3.12     11265  404      Yes
24     33.0     22.0        73.71      1.75      9233  212       No

In [7]:
df.shape

(23, 7)

In [8]:
from sklearn import preprocessing  



#labelencodingg

LE=preprocessing.LabelEncoder()

#fitting it to our dataset

df.Outbreak=LE.fit_transform(df.Outbreak)

In [9]:
X=df.iloc[:,:-1].values
Y=df.iloc[:,-1:].values
X,Y

(array([[2.9000e+01, 1.8000e+01, 4.9740e+01, 0.0000e+00, 2.1560e+03,
         1.1200e+02],
        [3.4000e+01, 2.3000e+01, 8.3270e+01, 1.5220e+01, 1.0717e+04,
         6.7700e+02],
        [4.0000e+01, 2.3000e+01, 5.0740e+01, 0.0000e+00, 1.2570e+03,
         1.2700e+02],
        [3.4000e+01, 2.4000e+01, 5.9160e+01, 9.0600e+00, 4.1980e+03,
         2.1100e+02],
        [3.4000e+01, 2.7000e+01, 7.3230e+01, 0.0000e+00, 1.1808e+04,
         7.1200e+02],
        [3.1000e+01, 2.4000e+01, 8.8770e+01, 4.1400e+01, 1.0881e+04,
         6.4800e+02],
        [3.3000e+01, 2.4000e+01, 7.7940e+01, 2.3880e+01, 8.8300e+03,
         4.5900e+02],
        [3.1000e+01, 2.4000e+01, 8.4570e+01, 1.1150e+01, 9.6930e+03,
         4.8200e+02],
        [3.6000e+01, 2.4000e+01, 5.3400e+01, 2.1200e+00, 9.3100e+03,
         5.4900e+02],
        [3.2000e+01, 2.3000e+01, 5.7500e+01, 0.0000e+00, 1.3154e+04,
         8.3800e+02],
        [3.4000e+01, 1.8000e+01, 5.9400e+01, 0.0000e+00, 2.1970e+03,
         1.3600e+02],

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,Y,test_size=0.2,random_state=0)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(X_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [12]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]]


In [13]:
print("predicted value for training data",model.score(X_train,y_train))
print("predicted value for testing data",model.score(X_test,y_test))

predicted value for training data 0.9444444444444444
predicted value for testing data 1.0


In [14]:
from sklearn.metrics import confusion_matrix,accuracy_score

cm = confusion_matrix(y_test, y_pred)

print(cm)

accuracy_score(y_test, y_pred)

[[3 0]
 [0 2]]


1.0

In [15]:
accuracy=model.score(X,Y)*100
print("overall accuracy of the model is",accuracy)

overall accuracy of the model is 95.65217391304348
